### ISSUE TITLE
Include a ring container?

### ISSUE THREAD

**Issue by peter-moran** [martinmoene/ring-span-lite#20]
For the sake of encapsulation I’d like to make a container that is a ring buffer and contains the data too. 

As far as I can tell, that would basically be a class that combines a std::array and a ring span, with all of the container functionality handled by the ring span. 

Is there a reason this does not exist?

**Comment by Quuxplusone** [comment]
This `ring_span` came out of P0059R1, which superseded Guy Davidson's [P0059R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0059r0.pdf) which *did* propose such owning container-ish rings. The main design ugliness there was that he needed both `fixed_ring` (which sounds like what you ask for, based on `array`) and also `dynamic_ring` (which would be resizeable like `vector`), with similar but distinct interfaces. `ring_span` was an attempt to unify their least common denominator. FWIW, I now consider `ring_span` to have been a _failed_ attempt.

We did indeed intend that "we provide `ring_span`, Peter uses it as a component to create his `OwningRing` container."  But notice that if you do `struct OwningRing { std::array<T, 10> data_; ring_span<T> ring_; }`, you must give it a user-defined copy constructor and assignment operator, because the compiler-generated defaults will do the Wrong Thing.

https://quuxplusone.github.io/blog/2018/05/30/reference-types-with-metadata-cause-problems/ is related.

As of a few months ago, there was talk that maybe Inbal Levi and Guy Davidson would revive P0059 for another attempt at the ring-buffer problem — I'd expect the new attempt to look significantly different from P0059R4 `ring_span`, if it happens. I'm not involved with it any more, myself.

**Comment by peter-moran** [comment]
Awesome, thanks for the history. I figured the reasoning was along those lines, but good to know for sure.

**Comment by martinmoene** [comment]
@peter-moran and @Quuxplusone Thanks for asking and responding. I wasn't aware of the information presented.

**Comment by martinmoene** [comment]
mmm, apparently I forgot about [Arthur's blog article](https://quuxplusone.github.io/blog/2018/05/30/reference-types-with-metadata-cause-problems/), as I had already added it to the references section myself. Perhaps a buffer overrun :)

**Comment by martinmoene** [comment]
Think this issue can be closed now with [release 0.5.0](https://github.com/martinmoene/ring-span-lite/releases/tag/v0.5.0).

Feel free to reopen it again if there's still more to address.
